version: 0.2

env:
  variables:
    # 1. Your correct ECR repository URI
    REPOSITORY_URI: "113726398464.dkr.ecr.ap-southeast-1.amazonaws.com/staging/cf2025-webapp"
    
    # 2. Your exact container name matching your ECS Task Definition
    CONTAINER_NAME: "ctnr-cf25-webApp"

phases:
  pre_build:
    commands:
      - echo "Check current directory..."
      - pwd
      - echo "List current directory..."
      - ls -la
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $REPOSITORY_URI
  build:
    commands:
      - echo "Printing my active directory..."
      - pwd
      - echo "Listing all files in the active directory..."
      - ls -la
      - echo "Building the Docker image..."
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo "Writing imageDetail.json for CodeDeploy..."
      - printf '{"ImageURI":"%s"}' "$REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION" > imageDetail.json

artifacts:
  files:
    - imageDetail.json
    - taskdef.json
    - appspec.yml